name: Bun CI Check

on: [push, pull_request]

jobs:
  build:
    name: build astro
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # run any `bun` or `bunx` command
      - run: bun i
      - run: bun run build
      - run: bun run lint
      # - run: bun run lint:prettier
      # Prettier config is failing in CI
